export const doNotSpeak = [
    {start:"0", end: "1", text: "You and me"},
    {start:"1", end: "2", text: "we used to be together"},
    {start:"2", end: "3", text: "every day together,"},
    {start:"3", end: "4", text: "always"},
    {start:"4", end: "5", text: "I really feel that I'm losin' "},
    {start:"5", end: "6", text: "my best friend"},
    {start:"6", end: "7", text: "I can't believe this could be "},
    {start:"7", end: "8", text: "the end"},
    {start:"8", end: "9", text: "It looks as though"},
    {start:"9", end: "10", text: "you're lettin' go"},
    {start:"10", end: "11", text: "And if it's real, well, "},
    {start:"11", end: "12", text: "I don't want to know "},
    {start:"12", end: "13", text: "Don't speak,"},
    {start:"13", end: "14", text: "I know just what you're sayin'"},
    {start:"14", end: "15", text: "So please stop explainin'"},
    {start:"15", end: "16", text: "Don't tell me 'cause it hurts"},
    {start:"16", end: "17", text: "Don't speak,"},
    {start:"17", end: "18", text: "I know what you're thinkin'"},
    {start:"18", end: "19", text: "I don't need your reasons"},
    {start:"19", end: "20", text: "Don't tell me 'cause it hurts"},
    {start:"20", end: "21", text: "Our memories, well, they can be inviting"},
    {start:"21", end: "22", text: "But some are altogether mighty frightening"},
    {start:"22", end: "23", text: "As we die, both you and I"},
    {start:"23", end: "24", text: "With my head in my hands, I sit and cry"},
    {start:"24", end: "25", text: "Don't speak,"},
    {start:"25", end: "26", text: "I know just what you're sayin'"},
    {start:"26", end: "27", text: "So please stop explainin'"},
    {start:"27", end: "28", text: "Don't tell me 'cause it hurts, no, no, no"},
    {start:"28", end: "29", text: "Don't speak,"},
    {start:"29", end: "30", text: "I know what you're thinkin'"},
    {start:"30", end: "31", text: "And I don't need your reasons"},
    {start:"31", end: "32", text: "Don't tell me 'cause it hurts"},
    {start:"32", end: "33", text: "It's all ending"},
    {start:"33", end: "34", text: "We gotta stop pretending"},
    {start:"34", end: "35", text: "Who we are"},
    {start:"35", end: "36", text: "You and me"},
    {start:"36", end: "37", text: "I can see us dyin'"},
    {start:"37", end: "38", text: "Aren't we?"},
    {start:"38", end: "39", text: "Don't speak,"},
    {start:"39", end: "40", text: "So please stop explainin'"},
    {start:"40", end: "41", text: "Don't tell me 'cause it hurts"},
    {start:"41", end: "42", text: "No, no, don't speak,"},
    {start:"42", end: "43", text: "I know what you're thinkin'"},
    {start:"43", end: "44", text: "And I don't need your reasons"},
    {start:"44", end: "45", text: "Don't tell me 'cause it hurts"},
    {start:"45", end: "46", text: "Don't tell me 'cause it hurts"},
    {start:"46", end: "47", text: "So please stop explainin'"},
    {start:"47", end: "48", text: "Don't speak, don't speak"},
    {start:"48", end: "49", text: "Don't speak, no"},
    {start:"49", end: "50", text: "I know what you're thinkin'"},
    {start:"50", end: "51", text: "And I don't need your reasons"},
    {start:"51", end: "52", text: "I know you're good, I know you're good"},
    {start:"52", end: "53", text: "I know you're real good, oh"},
    {start:"53", end: "54", text: "La, la, la, la"},
    {start:"54", end: "55", text: "La, la, la, la"},
    {start:"55", end: "56", text: "Don't, don't, ooh, ooh"},
    {start:"56", end: "57", text: "Hush, hush, darling"},
    {start:"57", end: "58", text: "Hush, hush, darling"},
    {start:"58", end: "59", text: "Hush, hush"},
    {start:"59", end: "60", text: "Don't tell me 'cause it hurts"},
    {start:"60", end: "61", text: "Hush, hush, darling"},
    {start:"61", end: "62", text: "Hush, hush, darling"},
    {start:"62", end: "63", text: "Hush, hush"},
    {start:"63", end: "64", text: "Don't tell me 'cause it hurts"},
    {start:"64", end: "65", text: "Hush, hush, darling"}
];


