export const doNotSpeak = [
    {start:"10", end: "20", text: "You and me"},
    {start:"10", end: "20", text: "we used to be together"},
    {start:"10", end: "20", text: "every day together,"},
    {start:"10", end: "20", text: "always"},
    {start:"10", end: "20", text: "I really feel that I'm losin' "},
    {start:"10", end: "20", text: "my best friend"},
    {start:"10", end: "20", text: "I can't believe this could be "},
    {start:"10", end: "20", text: "the end"},
    {start:"10", end: "20", text: "It looks as though"},
    {start:"10", end: "20", text: "you're lettin' go"},
    {start:"10", end: "20", text: "And if it's real, well, "},
    {start:"10", end: "20", text: "I don't want to know "},
    {start:"10", end: "20", text: "Don't speak,"},
    {start:"10", end: "20", text: "I know just what you're sayin'"},
    {start:"10", end: "20", text: "So please stop explainin'"},
    {start:"10", end: "20", text: "Don't tell me 'cause it hurts"},
    {start:"10", end: "20", text: "Don't speak,"},
    {start:"10", end: "20", text: "I know what you're thinkin'"},
    {start:"10", end: "20", text: "I don't need your reasons"},
    {start:"10", end: "20", text: "Don't tell me 'cause it hurts"},
    {start:"10", end: "20", text: "Our memories, well, they can be inviting"},
    {start:"10", end: "20", text: "But some are altogether mighty frightening"},
    {start:"10", end: "20", text: "As we die, both you and I"},
    {start:"10", end: "20", text: "With my head in my hands, I sit and cry"},
    {start:"10", end: "20", text: "Don't speak,"},
    {start:"10", end: "20", text: "I know just what you're sayin'"},
    {start:"10", end: "20", text: "So please stop explainin'"},
    {start:"10", end: "20", text: "Don't tell me 'cause it hurts, no, no, no"},
    {start:"10", end: "20", text: "Don't speak,"},
    {start:"10", end: "20", text: "I know what you're thinkin'"},
    {start:"10", end: "20", text: "And I don't need your reasons"},
    {start:"10", end: "20", text: "Don't tell me 'cause it hurts"},
    {start:"10", end: "20", text: "It's all ending"},
    {start:"10", end: "20", text: "We gotta stop pretending"},
    {start:"10", end: "20", text: "Who we are"},
    {start:"10", end: "20", text: "You and me"},
    {start:"10", end: "20", text: "I can see us dyin'"},
    {start:"10", end: "20", text: "Aren't we?"},
    {start:"10", end: "20", text: "Don't speak,"},
    {start:"10", end: "20", text: "So please stop explainin'"},
    {start:"10", end: "20", text: "Don't tell me 'cause it hurts"},
    {start:"10", end: "20", text: "No, no, don't speak,"},
    {start:"10", end: "20", text: "I know what you're thinkin'"},
    {start:"10", end: "20", text: "And I don't need your reasons"},
    {start:"10", end: "20", text: "Don't tell me 'cause it hurts"},
    {start:"10", end: "20", text: "Don't tell me 'cause it hurts"},
    {start:"10", end: "20", text: "So please stop explainin'"},
    {start:"10", end: "20", text: "Don't speak, don't speak"},
    {start:"10", end: "20", text: "Don't speak, no"},
    {start:"10", end: "20", text: "I know what you're thinkin'"},
    {start:"10", end: "20", text: "And I don't need your reasons"},
    {start:"10", end: "20", text: "I know you're good, I know you're good"},
    {start:"10", end: "20", text: "I know you're real good, oh"},
    {start:"10", end: "20", text: "La, la, la, la"},
    {start:"10", end: "20", text: "La, la, la, la"},
    {start:"10", end: "20", text: "Don't, don't, ooh, ooh"},
    {start:"10", end: "20", text: "Hush, hush, darling"},
    {start:"10", end: "20", text: "Hush, hush, darling"},
    {start:"10", end: "20", text: "Hush, hush"},
    {start:"10", end: "20", text: "Don't tell me 'cause it hurts"},
    {start:"10", end: "20", text: "Hush, hush, darling"},
    {start:"10", end: "20", text: "Hush, hush, darling"},
    {start:"10", end: "20", text: "Hush, hush"},
    {start:"10", end: "20", text: "Don't tell me 'cause it hurts"},
    {start:"10", end: "20", text: "Hush, hush, darling"}
];

